name: schooled
favicon: null
layout_spectrum: 0.6194436161313206
typography_spectrum: 0.9749318053945899
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.06512401066720486
  lightness: 0.013216032413765788
  saturation: 0.4796287934295833
  rhythmicContrast: 0.9950251718983054
purpose: []
